USE [master]
GO

/****** Object:  Database [LoggingApplication]    Script Date: 02/13/2013 09:09:18 ******/
CREATE DATABASE [LoggingApplication] ON  PRIMARY 
( NAME = N'LoggingApplication', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.SQLSERVER\MSSQL\DATA\LoggingApplication.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LoggingApplication_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.SQLSERVER\MSSQL\DATA\LoggingApplication_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LoggingApplication] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoggingApplication].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoggingApplication] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoggingApplication] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoggingApplication] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoggingApplication] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoggingApplication] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoggingApplication] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LoggingApplication] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LoggingApplication] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoggingApplication] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoggingApplication] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoggingApplication] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoggingApplication] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoggingApplication] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoggingApplication] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoggingApplication] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoggingApplication] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LoggingApplication] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoggingApplication] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoggingApplication] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoggingApplication] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoggingApplication] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoggingApplication] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LoggingApplication] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoggingApplication] SET  READ_WRITE 
GO

ALTER DATABASE [LoggingApplication] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LoggingApplication] SET  MULTI_USER 
GO

ALTER DATABASE [LoggingApplication] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoggingApplication] SET DB_CHAINING OFF 
GO

