//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("logappmodel", "FK_BusinessActionArgs_MetaRuleAction", "MetaRuleAction", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LoggingRepository.MetaRuleAction), "BusinessActionArgs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LoggingRepository.BusinessActionArg), true)]
[assembly: EdmRelationshipAttribute("logappmodel", "FK_BusinessRulesArgs_MetaRuleAction", "MetaRuleAction", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(LoggingRepository.MetaRuleAction), "BusinessRulesArgs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(LoggingRepository.BusinessRulesArg), true)]

#endregion

namespace LoggingRepository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LoggingApplicationModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LoggingApplicationModel object using the connection string found in the 'LoggingApplicationModel' section of the application configuration file.
        /// </summary>
        public LoggingApplicationModel() : base("name=LoggingApplicationModel", "LoggingApplicationModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LoggingApplicationModel object.
        /// </summary>
        public LoggingApplicationModel(string connectionString) : base(connectionString, "LoggingApplicationModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LoggingApplicationModel object.
        /// </summary>
        public LoggingApplicationModel(EntityConnection connection) : base(connection, "LoggingApplicationModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BusinessActionArg> BusinessActionArgs
        {
            get
            {
                if ((_BusinessActionArgs == null))
                {
                    _BusinessActionArgs = base.CreateObjectSet<BusinessActionArg>("BusinessActionArgs");
                }
                return _BusinessActionArgs;
            }
        }
        private ObjectSet<BusinessActionArg> _BusinessActionArgs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BusinessRulesArg> BusinessRulesArgs
        {
            get
            {
                if ((_BusinessRulesArgs == null))
                {
                    _BusinessRulesArgs = base.CreateObjectSet<BusinessRulesArg>("BusinessRulesArgs");
                }
                return _BusinessRulesArgs;
            }
        }
        private ObjectSet<BusinessRulesArg> _BusinessRulesArgs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log> Logs
        {
            get
            {
                if ((_Logs == null))
                {
                    _Logs = base.CreateObjectSet<Log>("Logs");
                }
                return _Logs;
            }
        }
        private ObjectSet<Log> _Logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MetaRuleAction> MetaRuleActions
        {
            get
            {
                if ((_MetaRuleActions == null))
                {
                    _MetaRuleActions = base.CreateObjectSet<MetaRuleAction>("MetaRuleActions");
                }
                return _MetaRuleActions;
            }
        }
        private ObjectSet<MetaRuleAction> _MetaRuleActions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BusinessActionArgs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBusinessActionArgs(BusinessActionArg businessActionArg)
        {
            base.AddObject("BusinessActionArgs", businessActionArg);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BusinessRulesArgs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBusinessRulesArgs(BusinessRulesArg businessRulesArg)
        {
            base.AddObject("BusinessRulesArgs", businessRulesArg);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogs(Log log)
        {
            base.AddObject("Logs", log);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MetaRuleActions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMetaRuleActions(MetaRuleAction metaRuleAction)
        {
            base.AddObject("MetaRuleActions", metaRuleAction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="logappmodel", Name="BusinessActionArg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BusinessActionArg : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BusinessActionArg object.
        /// </summary>
        /// <param name="actionID">Initial value of the ActionID property.</param>
        /// <param name="metaFK">Initial value of the MetaFK property.</param>
        /// <param name="args">Initial value of the Args property.</param>
        public static BusinessActionArg CreateBusinessActionArg(global::System.Int32 actionID, global::System.Int32 metaFK, global::System.String args)
        {
            BusinessActionArg businessActionArg = new BusinessActionArg();
            businessActionArg.ActionID = actionID;
            businessActionArg.MetaFK = metaFK;
            businessActionArg.Args = args;
            return businessActionArg;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActionID
        {
            get
            {
                return _ActionID;
            }
            set
            {
                if (_ActionID != value)
                {
                    OnActionIDChanging(value);
                    ReportPropertyChanging("ActionID");
                    _ActionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActionID");
                    OnActionIDChanged();
                }
            }
        }
        private global::System.Int32 _ActionID;
        partial void OnActionIDChanging(global::System.Int32 value);
        partial void OnActionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MetaFK
        {
            get
            {
                return _MetaFK;
            }
            set
            {
                OnMetaFKChanging(value);
                ReportPropertyChanging("MetaFK");
                _MetaFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MetaFK");
                OnMetaFKChanged();
            }
        }
        private global::System.Int32 _MetaFK;
        partial void OnMetaFKChanging(global::System.Int32 value);
        partial void OnMetaFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Args
        {
            get
            {
                return _Args;
            }
            set
            {
                OnArgsChanging(value);
                ReportPropertyChanging("Args");
                _Args = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Args");
                OnArgsChanged();
            }
        }
        private global::System.String _Args;
        partial void OnArgsChanging(global::System.String value);
        partial void OnArgsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("logappmodel", "FK_BusinessActionArgs_MetaRuleAction", "MetaRuleAction")]
        public MetaRuleAction MetaRuleAction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessActionArgs_MetaRuleAction", "MetaRuleAction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessActionArgs_MetaRuleAction", "MetaRuleAction").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MetaRuleAction> MetaRuleActionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessActionArgs_MetaRuleAction", "MetaRuleAction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessActionArgs_MetaRuleAction", "MetaRuleAction", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="logappmodel", Name="BusinessRulesArg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BusinessRulesArg : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BusinessRulesArg object.
        /// </summary>
        /// <param name="ruleID">Initial value of the RuleID property.</param>
        /// <param name="metaFK">Initial value of the MetaFK property.</param>
        /// <param name="args">Initial value of the Args property.</param>
        public static BusinessRulesArg CreateBusinessRulesArg(global::System.Int32 ruleID, global::System.Int32 metaFK, global::System.String args)
        {
            BusinessRulesArg businessRulesArg = new BusinessRulesArg();
            businessRulesArg.RuleID = ruleID;
            businessRulesArg.MetaFK = metaFK;
            businessRulesArg.Args = args;
            return businessRulesArg;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RuleID
        {
            get
            {
                return _RuleID;
            }
            set
            {
                if (_RuleID != value)
                {
                    OnRuleIDChanging(value);
                    ReportPropertyChanging("RuleID");
                    _RuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RuleID");
                    OnRuleIDChanged();
                }
            }
        }
        private global::System.Int32 _RuleID;
        partial void OnRuleIDChanging(global::System.Int32 value);
        partial void OnRuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MetaFK
        {
            get
            {
                return _MetaFK;
            }
            set
            {
                OnMetaFKChanging(value);
                ReportPropertyChanging("MetaFK");
                _MetaFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MetaFK");
                OnMetaFKChanged();
            }
        }
        private global::System.Int32 _MetaFK;
        partial void OnMetaFKChanging(global::System.Int32 value);
        partial void OnMetaFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Args
        {
            get
            {
                return _Args;
            }
            set
            {
                OnArgsChanging(value);
                ReportPropertyChanging("Args");
                _Args = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Args");
                OnArgsChanged();
            }
        }
        private global::System.String _Args;
        partial void OnArgsChanging(global::System.String value);
        partial void OnArgsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("logappmodel", "FK_BusinessRulesArgs_MetaRuleAction", "MetaRuleAction")]
        public MetaRuleAction MetaRuleAction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessRulesArgs_MetaRuleAction", "MetaRuleAction").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessRulesArgs_MetaRuleAction", "MetaRuleAction").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MetaRuleAction> MetaRuleActionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessRulesArgs_MetaRuleAction", "MetaRuleAction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MetaRuleAction>("logappmodel.FK_BusinessRulesArgs_MetaRuleAction", "MetaRuleAction", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="logappmodel", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log object.
        /// </summary>
        /// <param name="logID">Initial value of the LogID property.</param>
        /// <param name="time">Initial value of the time property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static Log CreateLog(global::System.Int32 logID, global::System.TimeSpan time, global::System.DateTime date, global::System.String title, global::System.String message)
        {
            Log log = new Log();
            log.LogID = logID;
            log.time = time;
            log.date = date;
            log.Title = title;
            log.Message = message;
            return log;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogID
        {
            get
            {
                return _LogID;
            }
            set
            {
                if (_LogID != value)
                {
                    OnLogIDChanging(value);
                    ReportPropertyChanging("LogID");
                    _LogID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogID");
                    OnLogIDChanged();
                }
            }
        }
        private global::System.Int32 _LogID;
        partial void OnLogIDChanging(global::System.Int32 value);
        partial void OnLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.TimeSpan _time;
        partial void OntimeChanging(global::System.TimeSpan value);
        partial void OntimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.String _Priority;
        partial void OnPriorityChanging(global::System.String value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                OnEventIDChanging(value);
                ReportPropertyChanging("EventID");
                _EventID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventID");
                OnEventIDChanged();
            }
        }
        private global::System.String _EventID;
        partial void OnEventIDChanging(global::System.String value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Severity
        {
            get
            {
                return _Severity;
            }
            set
            {
                OnSeverityChanging(value);
                ReportPropertyChanging("Severity");
                _Severity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Severity");
                OnSeverityChanged();
            }
        }
        private global::System.String _Severity;
        partial void OnSeverityChanging(global::System.String value);
        partial void OnSeverityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="logappmodel", Name="MetaRuleAction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MetaRuleAction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MetaRuleAction object.
        /// </summary>
        /// <param name="metaID">Initial value of the MetaID property.</param>
        /// <param name="logCategory">Initial value of the LogCategory property.</param>
        /// <param name="ruleAssembly">Initial value of the RuleAssembly property.</param>
        /// <param name="ruleClass">Initial value of the RuleClass property.</param>
        /// <param name="actionAssembly">Initial value of the ActionAssembly property.</param>
        /// <param name="actionClass">Initial value of the ActionClass property.</param>
        public static MetaRuleAction CreateMetaRuleAction(global::System.Int32 metaID, global::System.String logCategory, global::System.String ruleAssembly, global::System.String ruleClass, global::System.String actionAssembly, global::System.String actionClass)
        {
            MetaRuleAction metaRuleAction = new MetaRuleAction();
            metaRuleAction.MetaID = metaID;
            metaRuleAction.LogCategory = logCategory;
            metaRuleAction.RuleAssembly = ruleAssembly;
            metaRuleAction.RuleClass = ruleClass;
            metaRuleAction.ActionAssembly = actionAssembly;
            metaRuleAction.ActionClass = actionClass;
            return metaRuleAction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MetaID
        {
            get
            {
                return _MetaID;
            }
            set
            {
                if (_MetaID != value)
                {
                    OnMetaIDChanging(value);
                    ReportPropertyChanging("MetaID");
                    _MetaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MetaID");
                    OnMetaIDChanged();
                }
            }
        }
        private global::System.Int32 _MetaID;
        partial void OnMetaIDChanging(global::System.Int32 value);
        partial void OnMetaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LogCategory
        {
            get
            {
                return _LogCategory;
            }
            set
            {
                OnLogCategoryChanging(value);
                ReportPropertyChanging("LogCategory");
                _LogCategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LogCategory");
                OnLogCategoryChanged();
            }
        }
        private global::System.String _LogCategory;
        partial void OnLogCategoryChanging(global::System.String value);
        partial void OnLogCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RuleName
        {
            get
            {
                return _RuleName;
            }
            set
            {
                OnRuleNameChanging(value);
                ReportPropertyChanging("RuleName");
                _RuleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RuleName");
                OnRuleNameChanged();
            }
        }
        private global::System.String _RuleName;
        partial void OnRuleNameChanging(global::System.String value);
        partial void OnRuleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RuleAssembly
        {
            get
            {
                return _RuleAssembly;
            }
            set
            {
                OnRuleAssemblyChanging(value);
                ReportPropertyChanging("RuleAssembly");
                _RuleAssembly = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RuleAssembly");
                OnRuleAssemblyChanged();
            }
        }
        private global::System.String _RuleAssembly;
        partial void OnRuleAssemblyChanging(global::System.String value);
        partial void OnRuleAssemblyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RuleClass
        {
            get
            {
                return _RuleClass;
            }
            set
            {
                OnRuleClassChanging(value);
                ReportPropertyChanging("RuleClass");
                _RuleClass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RuleClass");
                OnRuleClassChanged();
            }
        }
        private global::System.String _RuleClass;
        partial void OnRuleClassChanging(global::System.String value);
        partial void OnRuleClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActionName
        {
            get
            {
                return _ActionName;
            }
            set
            {
                OnActionNameChanging(value);
                ReportPropertyChanging("ActionName");
                _ActionName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActionName");
                OnActionNameChanged();
            }
        }
        private global::System.String _ActionName;
        partial void OnActionNameChanging(global::System.String value);
        partial void OnActionNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActionAssembly
        {
            get
            {
                return _ActionAssembly;
            }
            set
            {
                OnActionAssemblyChanging(value);
                ReportPropertyChanging("ActionAssembly");
                _ActionAssembly = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ActionAssembly");
                OnActionAssemblyChanged();
            }
        }
        private global::System.String _ActionAssembly;
        partial void OnActionAssemblyChanging(global::System.String value);
        partial void OnActionAssemblyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ActionClass
        {
            get
            {
                return _ActionClass;
            }
            set
            {
                OnActionClassChanging(value);
                ReportPropertyChanging("ActionClass");
                _ActionClass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ActionClass");
                OnActionClassChanged();
            }
        }
        private global::System.String _ActionClass;
        partial void OnActionClassChanging(global::System.String value);
        partial void OnActionClassChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("logappmodel", "FK_BusinessActionArgs_MetaRuleAction", "BusinessActionArgs")]
        public EntityCollection<BusinessActionArg> BusinessActionArgs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BusinessActionArg>("logappmodel.FK_BusinessActionArgs_MetaRuleAction", "BusinessActionArgs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BusinessActionArg>("logappmodel.FK_BusinessActionArgs_MetaRuleAction", "BusinessActionArgs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("logappmodel", "FK_BusinessRulesArgs_MetaRuleAction", "BusinessRulesArgs")]
        public EntityCollection<BusinessRulesArg> BusinessRulesArgs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BusinessRulesArg>("logappmodel.FK_BusinessRulesArgs_MetaRuleAction", "BusinessRulesArgs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BusinessRulesArg>("logappmodel.FK_BusinessRulesArgs_MetaRuleAction", "BusinessRulesArgs", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="logappmodel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
